id: I85DD3D17
ocr_import_info:
  timestamp: '2023-06-27T16:07:12.579702+00:00'
  batch_id: batch-ca60
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-27 16:36:25.802946+00:00
last_modified: 2023-06-27 16:36:25.802954+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016759
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016759
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀཾ་ཚང་ཆོས་སྤྱོད་སོགས་ཁ་ཏོན་གཅེས་བཏུས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9817350801400878
  ocr_word_median_confidence_index: 0.99999905
bases:
  I01JW4:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW4
      total_pages: 920
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW4.txt
    statistics:
      ocr_word_median_confidence_index: 0.99999905
      ocr_word_mean_confidence_index: 0.9817350801400878
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
